version: '3'

services:
  spring-app:
    image: yosrspringapp:latest
    ports:
      - "9090:9090"
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: spring_db2
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456789
    ports:
      - "3307:3307"
