version: '3'

services:
  #backendapp
  app_foyer_backend:
    image: jallouli:latest
    container_name: jallouli-devops
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/springDBJallouli
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456789
