version: '3'

services:
  angular-app:
    image: ezui7/nejd:angular
    ports:
      - "4200:4200"

  spring-app:
    image: ezui7/nejd:springdevops
    ports:
      - "8091:8091"
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:latest
    ports:
      - "3308:3308"
    environment:
      - MYSQL_DATABASE=springDB
      - MYSQL_ROOT_PASSWORD=123456789
