version: '3'

services:
  mysqldb:
    image: mysql:latest
    container_name: mysql-container2
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: springDB
    ports:
      - "3308:3306"


  #backendapp

  app_foyer_backend:
    image: jallouli:latest
    container_name: jallouli-devops
    ports:
      - "8089:8089"
    depends_on:
      - mysqldb