version: '3'

services:
  spring-app:
    image: yosrspringapp:latest
    ports:
      - "8089:9090"
    depends_on:
      - mysql-db2



  mysql-db2:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: spring_db2test
    ports:
      - "3308:3308" # Use a different host port for the new MySQL service
