version: '3'

services:
  spring-app:
    image: bigj1/jallouli-devops:springdevops
    ports:
      - "8091:8091"
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:latest
    ports:
      - "3307:3307"
    environment:
      - MYSQL_DATABASE=springDBJallouli
      - MYSQL_ROOT_PASSWORD=123456789